- name: Desplegar contebinido de archivo UAT
  command: 
    cmd: cat /var/opt/ansible/UAT/{{ item }}
  with_items:
    - "{{ buscar_archivo_uat.stdout_lines }}"
  register: contenido_archivo_uat
  
- name: Imprimir contenido de archivo UAT
  debug:
    msg: "{{ contenido_archivo_uat.stdout_lines }}"
