- name: Buscar archivo UAT
  ansible.builtin.shell: ls -1rt /var/opt/ansible/UAT | grep ^IBM
  register: buscar_archivo_uat

- name: Desplegar contebinido de archivo UAT
  ansible.builtin.command: 
    cmd: cat /var/opt/ansible/UAT/{{ item }}
  with_items:
    - "{{ buscar_archivo_uat.stdout_lines }}"
  register: contenido_archivo_uat

- name: Crea archivo con el nombre asignado a UAT
  ansible.builtin.file: 
    path: /var/opt/ansible/UAT/{{ item }}
    state: touch
  with_items:
    - "{{ buscar_archivo_uat.stdout_lines }}"  
  delegate_to: clientasbrepo01.asbawx.clt
  
#- name: Imprimir contenido de archivo UAT
#  debug:
#   msg: "{{ contenido_archivo_uat.stdout }}"

- name: Agregar contenido al archivo UAT
  ansible.builtin.copy:
    dest: "/var/opt/ansible/UAT/{{ item }}"
    content: "{{ contenido_archivo_uat.stdout }}"    
  with_items:
    - "{{ buscar_archivo_uat.stdout_lines }}"
  delegate_to: clientasbrepo01.asbawx.clt
