- name: Formato directorio UIDEXT
  ansible.builtin.shell:
    cmd: date +%d%m%yUIDEXT
  register: sldeuat0

- name: Imprime formato directory UIDEXT
  debug:
    msg: "{{ sldeuat0.stdout }}"

- name: Crear directorio de UIDEXT
  ansible.builtin.file:
    path: /repouidex/{{ sldeuat0.stdout | regex_replace('\["|\]"', '') }}
    state: directory
    mode: 0700
