- name: Crear directorio de UAT
  ansible.builtin.file:
    path: /var/opt/ansible/UAT
    state: directory
    mode: 0700

- name: Envio de scripts UAT
  ansible.builtin.copy:
    src: files/iam_extract_global.sh
    dest: /tmp
    mode: 0700
    force: yes

- name: Ejecucion de script UAT
  become: yes
  become_method: sudo
  ansible.builtin.shell:
    cmd: /tmp/iam_extract_global.sh 2>/dev/null -c IBM
  register: sldeuat1
  failed_when: sldeuat1.rc not in [ 0, 1 ]

- name: Buscar archivo UAT
  ansible.builtin.shell: ls -1rt /tmp | grep ^IBM
  register: sldeuat2

- name: Mover archivo UAT
  become: yes
  become_method: sudo
  ansible.builtin.shell: mv /tmp/{{ item }} /var/opt/ansible/UAT
  with_items:
    - "{{ sldeuat2.stdout_lines }}"

- name: Desplegar contebinido de archivo UAT
  ansible.builtin.command: 
    cmd: cat /var/opt/ansible/UAT/{{ item }}
  with_items:
    - "{{ sldeuat2.stdout_lines }}"
  register: sldeuat3

- name: Crea archivo con el nombre asignado a UAT
  ansible.builtin.file: 
    path: /var/opt/ansible/UAT/{{ item }}
    state: touch
  with_items:
    - "{{ sldeuat2.stdout_lines }}"  
  delegate_to: clientasbrepo01.asbawx.clt
  
- name: Agregar contenido al archivo UAT
  ansible.builtin.copy:
    dest: "/var/opt/ansible/UAT/{{ item }}"
    content: "{{ sldeuat3 |to_nice_yaml }}"    
  with_items:
    - "{{ buscar_archivo_uat.stdout_lines }}"
  delegate_to: clientasbrepo01.asbawx.clt
