- name: Crear directorio de UAT
  ansible.builtin.file:
    path: /var/opt/ansible/UAT
    state: directory
    mode: 0700

- name: Envio de scripts UAT
  ansible.builtin.copy:
    src: files/iam_extract_global.sh
    dest: /tmp
    mode: 0700
    force: yes

- name: Ejecucion de script UAT
  become: yes
  become_method: sudo
  ansible.builtin.shell:
    cmd: /tmp/iam_extract_global.sh 2>/dev/null -c IBM
  register: sldeuat1
  failed_when: sldeuat1.rc not in [ 0, 1 ]

- name: Buscar archivo UAT
  ansible.builtin.shell: ls -1rt /tmp | grep ^IBM
  register: sldeuat2
  failed_when: sldeuat2.stdout_lines == ""

- name: Imprime contenido de archivo UAT
  debug:
    msg: "{{ sldeuat2.stdout }}"

- name: Mover archivo UAT
  become: yes
  become_method: sudo
  ansible.builtin.shell: mv /tmp/{{ sldeuat2.stdout | regex_replace('\["|\]"', '') }} /var/opt/ansible/UAT

#- name: Mover archivo UAT
#  become: yes
#  become_method: sudo
#  ansible.builtin.shell: mv /tmp/{{ item }} /var/opt/ansible/UAT
#  with_items:
#    - "{{ sldeuat2.stdout_lines }}"

#- name: Desplegar contebinido de archivo UAT
#  ansible.builtin.command:
#    cmd: cat /var/opt/ansible/UAT/{{ sldeuat2.stdout | regex_replace('\["|\]"', '') }}
#  register: sldeuat3
#  failed_when: sldeuat3.stdout_lines == ""

#- name: Imprime contenido de archivo UAT
#  debug:
#    msg: "{{ sldeuat3.stdout_lines }}"

#- name: Crea archivo con el nombre asignado a UAT
#  ansible.builtin.file:
#    path: /var/opt/ansible/UAT/{{ sldeuat2.stdout | regex_replace('\["|\]"', '') }}
#    state: touch
#  delegate_to: clientasbrepo01.asbawx.clt

- name: Agregar contenido al archivo UAT
  ansible.builtin.copy:
    content: "{{ sldeuat3.stdout_lines | to_nice_json(indent=0) }}"
    dest: "/var/opt/ansible/UAT/{{ item }}"
  with_items:
    - "{{ sldeuat2.stdout }}"
  delegate_to: clientasbrepo01.asbawx.clt

- name: Cambiar formato al archivo UAT
  ansible.builtin.command:
    cmd: sed -i 's/\"//g; s/,$//g; s/\[//g; s/\]//g' /var/opt/ansible/UAT/{{ sldeuat2.stdout | regex_replace('\["|\]"', '') }}
  delegate_to: clientasbrepo01.asbawx.clt
