- name: Formato directorio UIDEXT
  ansible.builtin.shell:
    cmd: date +%d%m%yUIDEXT
  register: sldeuat0

- name: Imprime formato directory UIDEXT
  debug:
    msg: "{{ sldeuat0.stdout }}"

- name: Crear directorio de UIDEXT
  ansible.builtin.file:
    path: /repouidext/{{ sldeuat0.stdout }}
    state: directory
    mode: 0700
  delegate_to: clientasbrepo01.asbawx.clt
