- name: Formato directorio UIDEXT
  ansible.builtin.shell:
    cmd: date +%d%m%yUIDEXT
  register: sldeuat0

- name: Imprime formato directory UIDEXT
  debug:
    msg: "{{ sldeuat2.stdout }}"

- name: Crear directorio de UIDEXT
  ansible.builtin.file:
    path: /var/opt/ansible/UIDEXT
    state: directory
    mode: 0700

- name: Envio de scripts UIDEXT
  ansible.builtin.copy:
    src: files/iam_extract_global.sh
    dest: /tmp
    mode: 0700
    force: yes

- name: Ejecucion de script UIDEXT
  become: yes
  become_method: sudo
  ansible.builtin.shell:
    cmd: /tmp/iam_extract_global.sh 2>/dev/null -c IBM
  register: sldeuat1
  failed_when: sldeuat1.rc not in [ 0, 1 ]

- name: Buscar archivo UIDEXT
  ansible.builtin.shell: ls -1rt /tmp | grep ^IBM
  register: sldeuat2
  failed_when: sldeuat2.stdout_lines == ""

- name: Imprime contenido de archivo UIDEXT
  debug:
    msg: "{{ sldeuat2.stdout }}"

- name: Mover archivo UIDEXT
  become: yes
  become_method: sudo
  ansible.builtin.shell: mv /tmp/{{ sldeuat2.stdout | regex_replace('\["|\]"', '') }} /var/opt/ansible/UIDEXT

#- name: Mover archivo UIDEXT
#  become: yes
#  become_method: sudo
#  ansible.builtin.shell: mv /tmp/{{ item }} /var/opt/ansible/UIDEXT
#  with_items:
#    - "{{ sldeuat2.stdout_lines }}"

- name: Desplegar contebinido de archivo UIDEXT
  ansible.builtin.command:
    cmd: cat /var/opt/ansible/UIDEXT/{{ sldeuat2.stdout | regex_replace('\["|\]"', '') }}
  register: sldeuat3
  failed_when: sldeuat3.stdout_lines == ""

- name: Imprime contenido de archivo UIDEXT
  debug:
    msg: "{{ sldeuat3.stdout_lines }}"

### Validar sintaxix ###
- name: Crear directorio de UIDEXT Repositorio Remoto
  ansible.builtin.file:
    path: /repouidext/{{ sldeuat0.stdout | regex_replace('\["|\]"', '') }}
    state: directory
    mode: 0700
delegate_to: clientasbrepo01.asbawx.clt

- name: Crea archivo con el nombre asignado a UIDEXT
  ansible.builtin.file:
    path: /repouidext/{{ sldeuat0.stdout | regex_replace('\["|\]"', '') }}/{{ sldeuat2.stdout | regex_replace('\["|\]"', '') }}
    state: touch
  delegate_to: clientasbrepo01.asbawx.clt

### Validar sintaxix ###
- name: Agregar contenido al archivo UIDEXT
  ansible.builtin.copy:
    content: "{{ sldeuat3.stdout_lines | to_nice_json(indent=0) }}"
    dest: "/repouidext/{{ sldeuat0.stdout | regex_replace('\["|\]"', '') }}/{{ sldeuat2.stdout | regex_replace('\["|\]"', '') }}"
#    dest: "/repouidext/{{ sldeuat0.stdout | regex_replace('\["|\]"', '') }}/{{ item }}"
#  with_items:
#    - "{{ sldeuat2.stdout }}"
  delegate_to: clientasbrepo01.asbawx.clt

### Validar sintaxix ###
- name: Cambiar formato al archivo UIDEXT
  ansible.builtin.command:
    cmd: sed -i 's/\"//g; s/,$//g; s/\[//g; s/\]//g' /repouidext/{{ sldeuat0.stdout | regex_replace('\["|\]"', '') }}/{{ sldeuat2.stdout | regex_replace('\["|\]"', '') }}
  delegate_to: clientasbrepo01.asbawx.clt
