- name: Buscar archivo UAT
  ansible.builtin.shell: ls -1rt /var/opt/ansible/UAT | grep ^IBM
  register: buscar_archivo_uat

- name: Desplegar contebinido de archivo UAT
  command: 
    cmd: cat /var/opt/ansible/UAT/{{ item }}
  with_items:
    - "{{ buscar_archivo_uat.stdout_lines }}"
  register: contenido_archivo_uat

- name: Imprime creacion del archivo UAT
  debug:
    msg: "{{ buscar_archivo_uat.stdout_lines }}"

#- name: Imprimir contenido de archivo UAT
#  debug:
#    msg: "{{ contenido_archivo_uat.stdout }}"
