- name: Formato directorio fecha UIDEXT en repositorio delegado
  ansible.builtin.shell:
    cmd: date +%d%m%yUIDEXT
  register: sldeuat0

- name: Imprimir directory fecha UIDEXT en repositorio delegado
  debug:
    msg: "{{ sldeuat0.stdout }}"

- name: Crear directorio fecha UIDEXT en repositorio delegado
  ansible.builtin.file:
    path: /repouidext/{{ sldeuat0.stdout }}
    state: directory
    mode: 0700
  delegate_to: clientasbrepo01.asbawx.clt

- name: Crear directorio de UIDEXT en el nodo administrado
  ansible.builtin.file:
    path: /var/opt/ansible/UIDEXT
    state: directory
    mode: 0700

- name: Envio de scripts UIDEXT a nodo administrado
  ansible.builtin.copy:
    src: files/iam_extract_global.sh
    dest: /tmp
    mode: 0700
    force: yes

- name: Ejecucion de script UIDEXT en el nodo administrado
  become: yes
  become_method: sudo
  ansible.builtin.shell:
    cmd: /tmp/iam_extract_global.sh 2>/dev/null -c IBM
  register: sldeuat1
  failed_when: sldeuat1.rc not in [ 0, 1 ]

- name: Nombre del archivo UIDEXT en el nodo administrado
  ansible.builtin.shell: ls -1rt /tmp | grep ^IBM
  register: sldeuat2
  failed_when: sldeuat2.stdout_lines == ""

- name: Imprimir nombre del archivo UIDEXT en nodo administrado
  debug:
    msg: "{{ sldeuat2.stdout }}"

- name: Mover archivo UIDEXT
  become: yes
  become_method: sudo
  ansible.builtin.shell: mv /tmp/{{ sldeuat2.stdout }} /var/opt/ansible/UIDEXT

- name: Desplegar contenido del archivo UIDEXT en el nodo administrado
  ansible.builtin.command:
    cmd: cat /var/opt/ansible/UIDEXT/{{ sldeuat2.stdout }}
  register: sldeuat3
  failed_when: sldeuat3.stdout_lines == ""

- name: Imprimir contenido de archivo UIDEXT en el nodo administrado
  debug:
    msg: "{{ sldeuat3.stdout_lines }}"
